# Cloudflare Pages configuration
name = "portfolio-website"
compatibility_date = "2024-03-15"
compatibility_flags = ["nodejs_compat"]

# Build settings
[build]
command = "npm run build"
output_dir = "dist"

# Environment variables
[env.production]
NODE_ENV = "production"

[env.development]
NODE_ENV = "development"

# Site settings
[site]
bucket = "./dist"

# Routes for SPA
[[routes]]
pattern = "/*"
script = ""  # No worker script needed
fallback_service = ""  # No fallback service needed

# Handle client-side routing
[[redirects]]
source = "/*"
destination = "/index.html"
status = 200
